name: Test avoiding workflow if PR from Dependabot
on:
  push:
    branches: [main]
  pull_request:
permissions:
  id-token: write # required for OIDC
jobs:
  avoid_if_dependabot:
    name: Avoid if dependabot
    runs-on: ubuntu-latest
    if: "!(github.event_name == 'pull_request' && github.actor == 'dependabot[bot]')"
    steps:
      - run: echo '${{ github.actor }}'; echo '${{ github.event_name }}'
      - run: echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" ; echo "${ACTIONS_ID_TOKEN_REQUEST_URL}"
